# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'MusicApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicApp
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  
end
